[package]
name = "wareki-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
napi = { version = "2.16", default-features = false, features = ["napi4"] }
napi-derive = "2.16"
wareki-core = { path = "../../core" }
